hostname r3
no ipv6 forwarding

interface eth1
 ip address 10.0.1.2/24

route-map ALLOW-ALL permit 10

router bgp 65003
 neighbor 10.0.1.1 remote-as 65002
  address-family ipv4 unicast
   neighbor 10.0.1.1 activate
   neightbor 10.0.1.1 route-map ALLOW-ALL in
   neightbor 10.0.1.1 route-map ALLOW-ALL out
   network 10.0.1.0/24
  exit-address-family
